name: Show Secret

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    env:
      VAR_1: ${{ secrets.VAR_1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secret
        run: echo "Secret value is $VAR_1"
