name: Show Secret

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secret
        env:
          var_1: ${{ secrets.var_1 }}
        run: |
          echo "Secret value is $var_1"
