name: Show Secret

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    env:
      TEST_VAR_1: ${{ secrets.TEST_VAR_1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secret
        run: echo "Secret value is $TEST_VAR_1"
