name: Show Secret

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secret
        run: echo "Secret value is ${{ secrets.TEST_VAR_1 }}"
